### ISSUE TITLE
Set the Prefer header properly when updating a resource

### ISSUE THREAD

**Issue by bashir2** [google/fhir-access-proxy#46]
For post-processing and updating the list of patients, we rely on full resources to be returned from the server. We should not rely on the FHIR store default config and instead set the "Prefer" header as described in the [spec](https://www.hl7.org/fhir/http.html#ops).

**Comment by bashir2** [comment]
Note this is also related to #44 .

**Comment by bashir2** [comment]
@bashir2 to check if in the process of updating patient list, this is really needed.

**Comment by vivekmittal07** [comment]
We are now passing the client supplied "Prefer" header for the incoming requests as part of #44.

Prefer header is required to control the response of a FHIR mutate API call.
For List access checker we are not consuming the response but just care about if it succeeded or not - https://github.com/google/fhir-access-proxy/blob/124c80e603bfb3af9c5f6d1ac81c93fc468275e5/plugins/src/main/java/com/google/fhir/proxy/plugin/AccessGrantedAndUpdateList.java#L130

We don't need to explicitly set "Prefer" header while updating patient list.
